### PR TITLE
54 illegal characters in path

### LINKED ISSUE #54: Unhandled exception when using dotnet run
### Brief bug description

When I try to run the generator using `dotnet run`, such as:

`dotnet run --projectid "975bf280-fd91-488c-994c-2f04416e5ee3"`
 
I get "Unhandled Exception: System.ArgumentException: The path is not of a legal form." and dotnet crashes.
 
If I add the `--outputdir` parameter:

`dotnet run --projectid "975bf280-fd91-488c-994c-2f04416e5ee3" --outputdir "C:\KC\demo\"`
 
I get "Unhandled Exception: System.ArgumentException: Illegal characters in path." 

Removing the backslash at the end fixes the problem and the generator works as intended.  
 
The precompiled executable does not have this problem. For example, running the latest exe (taken from https://github.com/Kentico/cloud-generators-net/releases/) directly without the `--outputdir` parameter works fine.

### PR DESCRIPTION
**Pull request by JanLenoch**
### Motivation

Fixes #54

### Checklist

- [x] Code follows coding conventions held in this repo
- [x] Automated tests have been added
- [x] Tests are passing
- [ ] Docu has been updated (if applicable)
- [x] Temporary settings (e.g. project ID used during development and testing) have been reverted to defaults

### How to test

Run CorrectArguments_CorrectionPerformed().

### CODE REVIEW

File: src/CloudModelGenerator/Program.cs [hunk 1]
```diff
@@ -32,6 +36,85 @@ static int Main(string[] args)
...
         }
 
+        internal static string[] CorrectArguments(string[] args)
+        {
+            var parsedArgs = new List<string>();
+
+            foreach (var arg in args)
+            {
+                // An argument name at the start of the current 'arg'.
+                var isArgumentName = Regex.Match(arg, @"^(-{1,2}\w+)");
```
Comment (Simply007) [inline src/CloudModelGenerator/Program.cs]: Do you want to compile the regex?

File: src/CloudModelGenerator/Program.cs [hunk 2]
```diff
@@ -32,6 +36,85 @@ static int Main(string[] args)
...
+
+                // Arguments and their values that the current 'arg' contains.
+                var argumentStarts = Regex.Matches(arg, @"\s+(-{1,2}\w+)").ToList();
```
Comment (Simply007) [inline src/CloudModelGenerator/Program.cs]: Do you want to compile the regex?

File: src/CloudModelGenerator/Program.cs [hunk 3]
```diff
@@ -32,6 +36,85 @@ static int Main(string[] args)
             return Execute(syntax);
         }
 
+        internal static string[] CorrectArguments(string[] args)
```
Comment (Simply007) [inline src/CloudModelGenerator/Program.cs]: This method is really hard to read.
Could you split it into the methods to make it more readable? It would probably help to for cover them by tests separately.

Do we want to have this method in this file, or separate it into another file to not have it next t the main method?

File: src/CloudModelGenerator/Program.cs [hunk 4]
```diff
@@ -32,6 +36,85 @@ static int Main(string[] args)
...
+                }
+            }
+
+            return parsedArgs.ToArray();
+        }
+
+        internal static List<string> ParseValues(string rawValue)
+        {
+            // Argument value incorrectly parsed by the runtime (due to the use of a "backslash and double quotes" sequence).
+            var valuesWithTrailingQuotes = Regex.Matches(rawValue, @"([^""]+)("")");
```
Comment (Simply007) [inline src/CloudModelGenerator/Program.cs]: Do you want to compile the regex?

Comment (Simply007) [reply src/CloudModelGenerator/Program.cs]: Section sanitizing trailing slash would be better to have in separate method and have a test on it.
