### PR TITLE
fixes #69 - accept full deliveryoptions (from .net delivery sdk) as p…

### LINKED ISSUE #69: Generator crashes if secure delivery is enabled
### Brief bug description

When secure delivery is enabled code generator crashes with unhandled exception:

> Unhandled Exception: System.AggregateException: One or more errors occurred. (Missing or invalid access token. Please include the valid access token value in the Authorization header field as an HTTP bearer authorization scheme.) ---> KenticoCloud.Delivery.DeliveryException: Missing or invalid access token. Please include the valid access token value in the Authorization header field as an HTTP bearer authorization scheme.
   at KenticoCloud.Delivery.DeliveryClient.<GetDeliverResponseAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
   at KenticoCloud.Delivery.DeliveryClient.<GetTypesAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
   at KenticoCloud.Delivery.DeliveryClient.<GetTypesAsync>d__37.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at CloudModelGenerator.CodeGenerator.GetClassCodeGenerators(Boolean structuredModel) in C:\projects\cloud-generators-net\src\CloudModelGenerator\CodeGenerator.cs:line 96
   at CloudModelGenerator.CodeGenerator.GenerateContentTypeModels(Boolean structuredModel) in C:\projects\cloud-generators-net\src\CloudModelGenerator\CodeGenerator.cs:line 38
   at CloudModelGenerator.Program.Execute(ArgumentSyntax argSyntax) in C:\projects\cloud-generators-net\src\CloudModelGenerator\Program.cs:line 77
   at CloudModelGenerator.Program.Main(String[] args) in C:\projects\cloud-generators-net\src\CloudModelGenerator\Program.cs:line 32

When secure delivery is disabled everything works as it should.

### Repro steps

1. Set up [Secure access](https://developer.kenticocloud.com/v1/reference#secure-access) in Delivery API
1. Generate models

### Suggested solution

- allow the [`DeliveryClient`](https://github.com/Kentico/cloud-generators-net/blob/master/src/CloudModelGenerator/CodeGenerator.cs#L30) to be configured via [suboptions](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.1#suboptions-configuration)
  - this is a future-proof solution that will ensure that whenever we add a new parameter to the Delivery SDK, it'll be supereasy to reflect it in the generator (just by upgrading the nuget reference of the SDK)
- preserve the `-p` configuration option...just for simplicity
- make the exception message more friendly (ideally, add an option allowing configuration of the exception verbosity level - by default without stack trace)

the configuration in this case would then be as follows:

```
{
  "OutputDir": "./output",
  "WithTypeProvider": true,
  "DeliveryClient": {
      "ProjectId": "abcd",
      "UseSecuredProductionApi": true,
      "SecuredProductionApiKey": "xyz"
   }
}
```

### PR DESCRIPTION
**Pull request by petrsvihlik**
…art of the configuration. makes it possible to use secured api

### Motivation

Fixes #69 

### Checklist

- [x] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docu has been updated (if applicable)
- [x] Temporary settings (e.g. project ID used during development and testing) have been reverted to defaults

### How to test
- Try to configure the utility to use secured delivery API
- Verify that appsettings.json and commandline configuration options work correctly

### CODE REVIEW

File: src/CloudModelGenerator/CommandLineOptionsProvider.cs [hunk 1]
```diff
@@ -14,16 +15,22 @@ public CommandLineOptionsProvider(IEnumerable<Argument> appOptions)
...
 
-                string value = commandOption.Value.ToString();
+                    if (!string.IsNullOrEmpty(value))
+                    {
+                        var paramName = commandOption.Names.Last();
 
-                if (!string.IsNullOrEmpty(value))
-                {
-                    Data.Add(commandOption.Names.Last(), value);
+                        // Backward compatibility
```
Comment (Simply007) [inline src/CloudModelGenerator/CommandLineOptionsProvider.cs]: Do we really want this backward compatibility?

If yes - I would probably link the issue and cover the functionality by the test...
```suggestion
                        /// Backward compatibility <see href="https://github.com/Kentico/cloud-generators-net/issues/69"/>
```

**Comment by petrsvihlik** [comment]
unfortunately, it's impossible to mock anything from the `System.CommandLine` namespace, therefore it's untestable. we'll have to go without tests.
